{
 "title": "Voting DashBord Copy",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\"}, pod)"
    }
   },
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" }
  ]
 },
 "panels": [
  { "title": "Pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod IP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "{{ pod_ip }}"
    }
   ]
  },
  {
   "title": "Resources by container",
   "type": "table",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=\"$pod\", unit=\"core\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=\"$pod\", unit=\"core\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=\"$pod\", unit=\"byte\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=\"$pod\", unit=\"byte\"}) by (container)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\", image!=\"\", container!=\"POD\"}[$__rate_interval])) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$pod\", image!=\"\", container!=\"POD\"}) by (container)"
    }
   ]
  },
  {
   "title": "CPU Usage by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\", image!=\"\", container!=\"POD\"}[$__rate_interval])) by (container)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Memory Usage by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$pod\", image!=\"\", container!=\"POD\"}) by (container)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Network - Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "Network - Packets Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_total{namespace=\"$namespace\", pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_packets_total{namespace=\"$namespace\", pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Global CPU Usage",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(1-rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval]))",
       "legendFormat": "Real"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{unit=\"core\"}) / sum(machine_cpu_cores)",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{unit=\"core\"}) / sum(machine_cpu_cores)",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "Global RAM Usage",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 7, "x": 7, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes)",
       "legendFormat": "Real"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{unit=\"byte\"}) / sum(machine_memory_bytes)",
       "legendFormat": "Requets"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{unit=\"byte\"}) / sum(machine_memory_bytes)",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "Nodes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 14, "y": 38 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(up{job=\"node-exporter\"})"
      }
     ]
    },
    {
     "title": "Resource Count",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 38 },
     "targets": [
      { "expr": "sum(kube_namespace_labels)", "legendFormat": "Namespaces" },
      {
       "expr": "sum(kube_pod_container_status_running)",
       "legendFormat": "Running Containers"
      },
      {
       "expr": "sum(kube_pod_status_phase{phase='Running'})",
       "legendFormat": "Running Pods"
      },
      { "expr": "sum(kube_service_info)", "legendFormat": "Services" },
      { "expr": "sum(kube_endpoint_info)", "legendFormat": "Endpoints" },
      { "expr": "sum(kube_ingress_info)", "legendFormat": "__auto" },
      { "expr": "sum(kube_deployment_labels)", "legendFormat": "Deployments" },
      { "expr": "sum(kube_statefulset_labels)", "legendFormat": "Statefulset" },
      { "expr": "sum(kube_daemonset_labels)", "legendFormat": "Daemon set" },
      {
       "expr": "sum(kube_persistentvolumeclaim_info)",
       "legendFormat": "Persistent Volume Claims"
      },
      { "expr": "sum(kube_hpa_labels)", "legendFormat": "HPA" },
      { "expr": "sum(kube_configmap_info)", "legendFormat": "Configmap" },
      { "expr": "sum(kube_secret_info)", "legendFormat": "Secretes" },
      { "expr": "sum(kube_networkpolicy_labels)", "legendFormat": "__auto" },
      {
       "expr": "count(up{job=\"node-exporter\"})",
       "legendFormat": "Nodes"
      }
     ]
    },
    {
     "title": "Namespaces",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 14, "y": 42 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "count(kube_namespace_created)" }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "stat",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(1-rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval]))",
       "legendFormat": "Real"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{unit=\"core\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{unit=\"core\"})",
       "legendFormat": "Limits"
      },
      { "expr": "sum(machine_cpu_cores)", "legendFormat": "Total" }
     ]
    },
    {
     "title": "RAM Usage",
     "type": "stat",
     "gridPos": { "h": 5, "w": 7, "x": 7, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)",
       "legendFormat": "Real"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{unit=\"byte\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{unit=\"byte\"})",
       "legendFormat": "Limits"
      },
      { "expr": "sum(machine_memory_bytes)", "legendFormat": "Total" }
     ]
    },
    {
     "title": "Running Pods",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 14, "y": 46 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{phase='Running'})"
      }
     ]
    },
    {
     "title": "Cluster CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(1-rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval]))",
       "legendFormat": "CPU usage in  %"
      }
     ]
    },
    {
     "title": "Cluster Memory Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes)",
       "legendFormat": "Memory usage in %"
      }
     ]
    },
    {
     "title": "CPU Utilization by namespace",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[$__rate_interval])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Memory Utilization by namespace",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{image!=\"\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Global Network Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_bytes_total[$__rate_interval]))",
       "legendFormat": "Total recived bytes"
      },
      {
       "expr": "- sum(rate(node_network_transmit_bytes_total[$__rate_interval]))",
       "legendFormat": "Total transmitted bytes"
      }
     ]
    },
    {
     "title": "Network  by namespace",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total[$__rate_interval])) by (namespace)",
       "legendFormat": "Recived bytes in {{namespace}}"
      },
      {
       "expr": "- sum(rate(container_network_transmit_bytes_total[$__rate_interval])) by (namespace)",
       "legendFormat": "Transmitted bytes in  {{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Name Spaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Namespace total CPU usage",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", image!=\"\"}[$__rate_interval])) / sum(machine_cpu_cores)"
      }
     ]
    },
    {
     "title": "Namespace total Memory usage",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\"}) / sum(machine_memory_bytes)"
      }
     ]
    },
    {
     "title": "Namespace Resource Count",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\"})",
       "legendFormat": "Running Pods"
      },
      {
       "expr": "sum(kube_service_info{namespace=~\"$namespace\"})",
       "legendFormat": "Services"
      },
      {
       "expr": "sum(kube_ingress_info{namespace=~\"$namespace\"})",
       "legendFormat": "Ingresses"
      },
      {
       "expr": "sum(kube_deployment_labels{namespace=~\"$namespace\"})",
       "legendFormat": "Deployments"
      },
      {
       "expr": "sum(kube_statefulset_labels{namespace=~\"$namespace\"})",
       "legendFormat": "Statefulsets"
      },
      {
       "expr": "sum(kube_daemonset_labels{namespace=~\"$namespace\"})",
       "legendFormat": "Daemonsets"
      },
      {
       "expr": "sum(kube_persistentvolumeclaim_info{namespace=~\"$namespace\"})",
       "legendFormat": "Persistent Volume Claims"
      },
      {
       "expr": "sum(kube_hpa_labels{namespace=~\"$namespace\"})",
       "legendFormat": "Horizontal Pod Autoscalers"
      },
      {
       "expr": "sum(kube_configmap_info{namespace=~\"$namespace\"})",
       "legendFormat": "Configmaps"
      },
      {
       "expr": "sum(kube_secret_info{namespace=~\"$namespace\"})",
       "legendFormat": "Secrets"
      },
      {
       "expr": "sum(kube_networkpolicy_labels{namespace=~\"$namespace\"})",
       "legendFormat": "Network Policies"
      }
     ]
    },
    {
     "title": "Namespace Core usage",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Real"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", unit=\"core\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", unit=\"core\"})",
       "legendFormat": "Limits"
      },
      { "expr": "sum(machine_cpu_cores)", "legendFormat": "Cluster Total" }
     ]
    },
    {
     "title": "Namespace RAM usage",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\"})",
       "legendFormat": "Real"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", unit=\"byte\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", unit=\"byte\"})",
       "legendFormat": "Limits"
      },
      { "expr": "sum(machine_memory_bytes)", "legendFormat": "Cluster Total" }
     ]
    },
    {
     "title": "CPU usage by Pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", image!=\"\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Memory usage by Pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", image!=\"\"}) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  }
 ]
}